apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Avinashraju7396/google-store-DevOps-project-importan-inter-main-project
    path: backend
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: google
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
